# Generated by Django 3.2.3 on 2021-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='noc',
            field=models.CharField(default='question', max_length=100),
        ),
    ]
